### ISSUE TITLE
Starlight for syntax highlighting (a port for the helix editor)

### ISSUE THREAD

**Issue by eemilhaa** [CosmicToast/starlight#4]
Thanks for making this theme!

I've been using these colors for syntax highlighting with the [helix editor](https://github.com/helix-editor/helix), and thought the theme might be useful to others too.

**Disclaimer**: I'm in no way colorblind. Simply put, I wanted a dark theme that is readable in all (especially brighter) conditions. This syntax theme works well for me in this regard but, of course, I say that as a person without any visual impairments.

My main point with this issue is to get your thoughts on opinionated ports like this. I understand if you do not want this theme included here (or in helix), as it is ultimately just my personal take on syntax highlighting, and might not align with your vision of starlight.

Below is a screenshot as well as some thoughts on the syntax theme.

![starlight](https://github.com/CosmicToast/starlight/assets/70660230/6ef84ad4-67f4-4742-ab09-5fbc5678caf1)

### On color use:
- I use the bright variants of the colors: High contrast and usability even in bright light were my priority
- Fewer highlighting scopes than most syntax themes: Keep scopes (and colors) distinguishable
- Even brightness: While many syntax themes make the decision to contrast things by brightness, I tried to somewhat avoid this. If I have to choose, I'd rather be unable to differentiate a color than be unable to read something at all
- Due to the above point (and due to not needing as many highlighting scopes as there are colors) I discarded the red color from the syntax palette, leaving it just for UI elements like errors

### Highlighting scopes, roughly put:
- Green for things that do stuff (functions, constructors)
- Cyan for things that explicitly are stuff (types, consts, numbers)
- Magenta for things that are part of something (function parameters, attributes, fields of composite types)
- White for variables, namespace
- Blue keywords and operators
- Yellow strings

**Comment by CosmicToast** [comment]
Hi, thanks for taking interest!

I don't think editor themes are in-scope, *but* I would be interested in linking to various users of the theme as a backend for something else (such as editor themes).
If you'd like, you can publish your theme in whatever standard form-factor helix holds it, and I'll make a list of backend users with it.

As for highlighting scopes and co, I'm actually utilizing the colors in neovim using mini base16.
You can find the details [here](https://github.com/CosmicToast/dotfiles/blob/main/dot_config/nvim/colors/starlight.lua).
You can feel free to either refine your concept using what I've been using for a while now, or simply publish as-is, I don't mind either way.

If you're interested, I'll close this after the list has been created.
Else, do close the issue (which I'll take as lack of interest).

**Comment by eemilhaa** [comment]
Seems sensible!

I'll look into the option of making a pr to helix directly, as having more colorblind friendly themes bundled with the editor could be added value to many users. If that proves not to be the best approach, I'll just release the theme as a public repo. Anyways, I'll update here once something happens.

**Comment by eemilhaa** [comment]
Hi! The theme is now included in Helix. [Here](https://github.com/helix-editor/helix/blob/master/runtime/themes/starlight.toml) is the theme file directly.

**Comment by CosmicToast** [comment]
Thanks a lot!
The USERS file is now created [here](https://github.com/CosmicToast/starlight/blob/main/USERS.md).
This should make it easier to add any future offshoots as well, of various types.
